spring:
  datasource:
    username: postgres
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/petclinic
  liquibase:
    change-log: classpath*:db/changelog/changelog.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate